package project.model;

import java.util.Objects;

/**
 * This is a Class implements an Airline.
 */
public class Airline {
    private int id;
    private String name;
    private boolean active;
    private String country;
    private String alias;
    private String callSign;
    private String iata;
    private String icao;
    private String recordName;

    /**
     * @param id    An int that represents the Airline ID
     * @param name  A String that represents the Airline Name
     * @param active    A boolean that represents whether an Airline is active
     * @param country   A String that represents the country the Airline is in
     * @param alias A String that represents the alias of the Airline
     * @param callSign  A String that represents the airline callSign
     * @param iata  A String that represents a 2-letter code, if available
     * @param icao  A String that represents a 3-letter code, if available
     */
    public Airline(int id, String name, boolean active, String country, String alias, String callSign, String iata, String icao) {
        setId(id);
        setName(name);
        setActive(active);
        setCountry(country);
        setAlias(alias);
        setCallSign(callSign);
        setIata(iata);
        setIcao(icao);
    }

    /**
     * This method checks if the Airline is equal to another Airline object (o)
     * @param   o An Airline object
     * @return  A boolean that represents whether o is equal to the current Airline
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Airline airline = (Airline) o;
        return getId() == airline.getId() &&
                isActive() == airline.isActive() &&
                Objects.equals(getName(), airline.getName()) &&
                Objects.equals(getCountry(), airline.getCountry()) &&
                Objects.equals(getAlias(), airline.getAlias()) &&
                Objects.equals(getCallSign(), airline.getCallSign()) &&
                Objects.equals(getIata(), airline.getIata()) &&
                Objects.equals(getIcao(), airline.getIcao());
    }

    /**
     * Hashcode that complements equals method.
     * @return  returns an integer value, generated by a hashing algorithm.
     */
    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName(), isActive(), getCountry(), getAlias(), getCallSign(), getIata(), getIcao());
    }

    /**
     * This method returns a String of information about Airline and Country it's from.
     * @return  A String of information about Airline and Country it's from.
     */
    @Override
    public String toString() {
        String nameString;
        if (name == null) {
            nameString = "Unknown airline, ";
        } else {
            nameString = name + ", ";
        }

        String countryString;
        if (country == null) {
            countryString = "originating from an unknown country";
        } else {
            countryString = "originating from " + country;
        }

        return nameString + countryString;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public void setCallSign(String callSign) {
        this.callSign = callSign;
    }

    public void setIata(String iata) {
        this.iata = iata;
    }

    public void setIcao(String icao) {
        this.icao = icao;
    }

    public void setRecordName(String recordName) { this.recordName = recordName; }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public boolean isActive() {
        return active;
    }

    public String getCountry() {
        return country;
    }

    public String getAlias() {
        return alias;
    }

    public String getCallSign() {
        return callSign;
    }

    public String getIata() {
        return iata;
    }

    public String getIcao() {
        return icao;
    }

    public String getRecordName() { return recordName; }
}
