package project.model;

import java.util.Objects;

/**
 * This is a Class implements Route taken from Route.dat.
 */
public class Route {
    private String airline;
    private int id;
    private String sourceAirport;
    private int sourceID;
    private String destAirport;
    private int destID;
    private int numStops;
    private String equipment;
    private boolean codeshare;

    /**
     * @param airline
     * @param id
     * @param sourceAirport
     * @param sourceID
     * @param destAirport
     * @param destID
     * @param numStops
     * @param equipment
     * @param codeshare
     */
    public Route(String airline, int id, String sourceAirport, int sourceID, String destAirport, int destID, int numStops, String equipment, boolean codeshare) {
            setAirline(airline);
            setId(id);
            setSourceAirport(sourceAirport);
            setSourceID(sourceID);
            setDestAirport(destAirport);
            setDestID(destID);
            setNumStops(numStops);
            setEquipment(equipment);
            setCodeshare(codeshare);

    }

    /**
     * This method checks if the Route is equal to another Route object (o) and ensures that it is a Route object
     * @param   o An Route object
     * @return  A boolean that represents whether o is equal to the current Route
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Route route = (Route) o;
        return getId() == route.getId() &&
                getSourceID() == route.getSourceID() &&
                getDestID() == route.getDestID() &&
                getNumStops() == route.getNumStops() &&
                isCodeshare() == route.isCodeshare() &&
                Objects.equals(getAirline(), route.getAirline()) &&
                Objects.equals(getSourceAirport(), route.getSourceAirport()) &&
                Objects.equals(getDestAirport(), route.getDestAirport()) &&
                Objects.equals(getEquipment(), route.getEquipment());
    }

    /**
     * Hashcode that complements equals method.
     * @return  returns an integer value, generated by a hashing algorithm.
     */
    @Override
    public int hashCode() {
        return Objects.hash(getAirline(), getId(), getSourceAirport(), getSourceID(), getDestAirport(), getDestID(), getNumStops(), getEquipment(), isCodeshare());
    }

    /**
     * This method returns a String of information about the route
     * The source Airport of the route and the destination of the route
     * and the Airline that goes through the route.
     * @return  A String of information about the source, destination and Airline in the route
     */
    @Override
    public String toString() {
        String sourceString;
        if (sourceAirport == null) {
            sourceString = "an unknown source airport ";
        } else {
            sourceString = "source airport " + sourceAirport + " ";
        }

        String destString;
        if (destAirport == null) {
            destString = "to an unknown destination airport ";
        } else {
            destString = "to destination airport " + destAirport + " ";
        }

        String airlineString;
        if (airline == null) {
            airlineString = "through an unknown airline";
        } else {
            airlineString = "through airline " + airline;
        }

        return "Route from " + sourceString + destString + airlineString;
    }

    public String getAirline() {
        return airline;
    }

    public void setAirline(String airline) {
        this.airline = airline;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getSourceAirport() {
        return sourceAirport;
    }

    public void setSourceAirport(String sourceAirport) {
        this.sourceAirport = sourceAirport;
    }

    public int getSourceID() {
        return sourceID;
    }

    public void setSourceID(int sourceID) {
        this.sourceID = sourceID;
    }

    public String getDestAirport() {
        return destAirport;
    }

    public void setDestAirport(String destAirport) {
        this.destAirport = destAirport;
    }

    public int getDestID() {
        return destID;
    }

    public void setDestID(int destID) {
        this.destID = destID;
    }

    public int getNumStops() {
        return numStops;
    }

    public void setNumStops(int numStops) {
        this.numStops = numStops;
    }

    public String getEquipment() {
        return equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    public boolean isCodeshare() {
        return codeshare;
    }

    public void setCodeshare(boolean codeshare) {
        this.codeshare = codeshare;
    }
}
